schedules:
- cron: '0 0 1 * *'
  displayName: Conservation
  branches:
    include:
    - master
  always: true

jobs:
- job: Conservation
  displayName: Conservation
  pool:
    name: Kubernetes
  timeoutInMinutes: 0

  steps:
  - task: Docker@2
    displayName: Docker login
    inputs:
      containerRegistry: 'DockerHub'
      command: 'login'

  - script: |
      ORG="johnwatson484"
      echo "Retrieving repository list"
      REPO_LIST=$(curl -s https://hub.docker.com/v2/repositories/${ORG}/?page_size=100 | jq -r '.results|.[]|.name')
      echo "Pulling latest 5 tags for each image in organization: ${ORG}"
      for REPO in ${REPO_LIST}
      do
        TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${ORG}/${REPO}/tags?page_size=5&page=1&ordering=last_updated" | jq -r '.results|.[]|.name')
        for TAG in ${TAGS}
        do
          docker pull ${ORG}/${REPO}:${TAG} --quiet
        done
        docker system prune --all --force
      done
    displayName: Pull images
