pool:
  vmImage: 'ubuntu-latest'

schedules:
- cron: "0 0 1 * *"
  displayName: Conservation
  branches:
    include:
    - master
  always: true

steps:
  - script: |
      echo 'hello'
    displayName: Test
    