pool:
  vmImage: 'ubuntu-latest'

variables:
  organisation: johnwatson484

schedules:
- cron: "0 0 1 * *"
  displayName: Conservation
  branches:
    include:
    - master
  always: true

steps:
  - script: |
      ORG="johnwatson484"
      echo "Retrieving repository list"
      REPO_LIST=$(curl -s https://hub.docker.com/v2/repositories/${ORG}/?page_size=100 | jq -r '.results|.[]|.name')
      echo "Pulling all images for organization: ${ORG}"
      for i in ${REPO_LIST}
      do
        docker pull ${ORG}/${i} --all-tags
      done
    displayName: Pull images
    